sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8.9.1'
before_install:
  - npm i -g npm
before_script:
  - npm prune
  - typings install
  - tsc -p .
script:
  - npm run test:single
after_success:
  - npm run semantic-release
branches:
  only:
  - master
